set-option -g default-shell /bin/zsh

set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g mouse on

set -s escape-time 0
set -g history-limit 2000



bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind R command-prompt -I "#{session_name}" "rename-session '%%'"

bind -n M-s choose-tree -s
bind -n M-Right next-window
bind -n M-Left previous-window
bind Space last-window
bind-key C-Space switch-client -l

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-n select-pane -L
bind -n M-o select-pane -R
bind -n M-a select-pane -U
bind -n M-e select-pane -D

bind -n M-C-Left resize-pane -L 5
bind -n M-C-Right resize-pane -R 5
bind -n M-C-Up resize-pane -U 3
bind -n M-C-Down resize-pane -D 3

bind h split-window -v
bind v split-window -h
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

bind t new-window
bind g new-window -c "#{pane_current_path}"
bind c kill-pane
bind q kill-window
bind -n M-q detach
bind -n M-x confirm-before -p "Kill entire session? (y/n)" kill-session

bind y copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -T copy-mode-vi Escape send -X cancel

bind -T copy-mode-vi / command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -T copy-mode-vi ? command-prompt -p "(search up)"   "send -X search-backward '%%%'"

#plugins
run-shell ~/.config/tmux/plugins/resurrect/resurrect.tmux
set -g @resurrect-capture-pane-contents 'on'
run-shell ~/.config/tmux/plugins/continuum/continuum.tmux
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g pane-border-lines double
set -g clock-mode-style 24
# nightfox carbonfox
set -g status on
set -g status-bg "#161616"          
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100

set -g message-style "fg=#33b1ff,bg=#282828,align=centre"      
set -g message-command-style "fg=#33b1ff,bg=#282828,align=centre"
set -g pane-border-style "fg=#282828"                          
set -g pane-active-border-style "fg=#78a9ff"                   
set -g clock-mode-style 24
setw -g clock-mode-colour "#33b1ff"                            
setw -g mode-style "fg=#33b1ff bg=#282828 bold"                

setw -g window-status-activity-style bold
setw -g window-status-bell-style bold
setw -g window-status-separator ""
setw -g window-status-style "fg=#f2f4f8,bg=#161616,none"       

set -g status-left "#{?client_prefix,#[bg=#ee5396],#[bg=#25be6a]}#[fg=#161616,bold] #S #{?client_prefix,#[fg=#ee5396],#[fg=#25be6a]}#[bg=#161616]"

setw -g window-status-format "#[fg=#33b1ff,bg=#161616]#[fg=#161616,bg=#33b1ff] #I #[fg=#33b1ff,bg=#282828] #W #[fg=#282828,bg=#161616]"

setw -g window-status-current-format "#[fg=#ff7eb6,bg=#161616]#[fg=#161616,bg=#ff7eb6,bold] #I #[fg=#ff7eb6,bg=#282828] #W #[fg=#282828,bg=#161616]#{?window_zoomed_flag,,}#[fg=#ff7eb6,bg=#282828]#{?window_zoomed_flag,🔍,}#[fg=#282828,bg=#161616]#{?window_zoomed_flag,,}"

set -g status-right "#[fg=#282828,bg=#161616]#[fg=#33b1ff,bg=#282828] #H #[fg=#33b1ff,bg=#282828,bold] 󱑂 %R #(date +%Z) "
